CREATE MATERIALIZED VIEW dm.metadata AS
SELECT
  mpv.study_id,
  mpv.study_name,
  mpv.study_name_clean,
  mpv.study_status,
  mpv.study_date_created,
  mpv.study_date_updated,
  mpv.event_id,
  mpv.event_oid,
  mpv.event_order,
  mpv.event_name,
  mpv.event_date_created,
  mpv.event_date_updated,
  mpv.event_repeating,
  mpv.crf_parent_oid,
  mpv.crf_parent_name,
  mpv.crf_parent_date_created,
  mpv.crf_parent_date_updated,
  mpv.crf_version,
  mpv.crf_version_id,
  mpv.crf_version_oid,
  mpv.crf_version_date_created,
  mpv.crf_version_date_updated,
  mpv.crf_is_required,
  mpv.crf_is_double_entry,
  mpv.crf_is_hidden,
  mpv.crf_null_values,
  mpv.crf_section_label,
  mpv.crf_section_title,
  mpv.item_group_id,
  mpv.item_group_oid,
  mpv.item_group_name,
  mpv.item_form_order,
  mpv.item_id,
  mpv.item_ordinal_per_ig_over_crfv,
  concat_ws($s$_$s$,
    mpv.item_oid,
    openclinica_fdw.dm_clean_name_string(mpv_exp.option_value)
  ) AS item_oid,                      /* i_group_my_second_item_choice_3 */
  concat_ws($s$_$s$,
    mpv.item_name,
    openclinica_fdw.dm_clean_name_string(mpv_exp.option_value)
  ) AS item_name,                     /* my_second_item_choice_3 */
  mpv.item_name_clean,
  mpv.item_description,
  concat_ws($s$_$s$,
    left(mpv.item_name_clean, 12),
    openclinica_fdw.dm_clean_name_string(mpv_exp.option_value),
    left(openclinica_fdw.dm_clean_name_string(mpv.item_description), 45)
  ) AS item_ident_mvalue_description, /* my_second_it_choice_3_my_2nd_item */
  concat_ws($s$_$s$,
    left(mpv.item_name_clean, 12),
    openclinica_fdw.dm_clean_name_string(mpv_exp.option_value)
  ) AS item_ident_mvalue,             /* my_second_it_choice_3 */
  concat_ws($s$_$s$,
    left(mpv.item_name_clean, 12),
    mpv.item_ordinal_per_ig_over_crfv,
    mpv_exp.item_multi_order_over_rsi
  ) AS item_ident_itemid_morderid,    /* my_second_it_2_3 */
  mpv.item_units,
  mpv_exp.item_data_type_multi_original,
  coalesce(mpv_exp.item_data_type, mpv.item_data_type) AS item_data_type,
  mpv.item_response_type,
  mpv.is_multi_choice,
  mpv_exp.item_oid_multi_original,
  mpv_exp.item_name_multi_original,
  mpv_exp.option_order AS item_multi_option_order,
  mpv_exp.option_value AS item_multi_option_value,
  mpv_exp.option_text AS item_multi_option_text,
  mpv_exp.item_multi_order_over_rsi,
  mpv.item_response_set_label,
  mpv.item_response_set_id,
  mpv.item_response_set_version,
  mpv.item_question_number,
  mpv.item_header,
  mpv.item_subheader,
  mpv.item_left_item_text,
  mpv.item_right_item_text,
  mpv.item_regexp,
  mpv.item_regexp_error_msg,
  mpv.item_required,
  mpv.item_default_value,
  mpv.item_response_layout,
  mpv.item_width_decimal,
  mpv.item_show_item,
  mpv.item_scd_item_oid,
  mpv.item_scd_item_option_value,
  mpv.item_scd_item_option_text,
  mpv.item_scd_validation_message
FROM dm.metadata_pre_view AS mpv
  LEFT JOIN dm.metadata_mv_exp AS mpv_exp
    ON mpv.item_id = mpv_exp.item_id;
